### ISSUE TITLE
ei man, vai de gradle + spring boot

### ISSUE THREAD

**Issue by sombriks** [sergiosilvajr/spring-repo#1]
de maven é o pessoal da redhat / jboss, que ainda não largou o osso. springsource tá de gradle faz tempo e o springboot já escala pra cima e pra baixo, e microservices com o boot já estão noutro estágio: http://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html

**Comment by sergiosilvajr** [comment]
gradle é sempre bem vindo :). Eu segui um livreto e dai fui exatamente fazendo como ele informava. Vou dar uma pesquisada, valeu!
